---
version: '2.4'
services:
    cups:
        platform: linux/amd64
        image: crazyquark/cups
        network_mode: host
        privileged: true
        volumes:
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - CUPSADMIN=admin
            - CUPSPASSWORD=password


